name: Continuous Testing


on:
  push:
    branches: [develop]

jobs:
  prepare-server:
    runs-on: [ubuntu-latest]
    steps:
      - name: Import commit files
        uses: actions/checkout@v2
      - name: create test files
        run: |
          mkdir test-files
          while read line
          do
            touch test-files/$line
          done < .github/workflows/test-files.txt
      - name: Upload to FTP Server
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          forceSsl: true
          localDir: test-files
          remoteDir: .
  pattern-delete-files:
    name: Test pattern-delete action
    runs-on: [ubuntu-latest]
    needs: [prepare-server]
    steps:
      - name: pattern delete
        uses: astriffe/ftp-delete-action@develop
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          workingDir: .
          ignoreSsl: 1
          pattern: '(/main-/ && !/hashToKeep/) || (/runtime-/ && !/hashToKeep/) || (/styles/ && !/hashToKeep/) || (/polyfills-/ && !/hashToKeep/)'
  verify:
    name: Verify residual files
    runs-on: [ubuntu-latest]
    needs: [pattern-delete-files]
    steps:
      - name: Verify residing file count
        run: |
          wget -r --ftp-user=${{ secrets.FTP_USERNAME }} --ftp-password=${{ secrets.FTP_PASSWORD }} "ftp://ftp.${{ secrets.FTP_SERVER }}"
          cd ftp.${{ secrets.FTP_SERVER }}
          ls -l | grep main | wc -l | xargs -I % test % -le 2 || exit 1
          ls -l | grep runtime | wc -l | xargs -I % test % -le 2 || exit 1
          ls -l | grep styles | wc -l | xargs -I % test % -le 1 || exit 1
          ls -l | grep polyfills | wc -l | xargs -I % test % -le 2 || exit 1
  cleanup:
    name: Cleanup FTP Server
    runs-on: [ubuntu-latest]
    needs: [verify]
    steps:
      - name: pattern delete
        uses: astriffe/ftp-delete-action@develop
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          workingDir: .
          ignoreSsl: 1
          pattern: "//"